### ISSUE TITLE
训练出现的错误

### ISSUE THREAD

**Issue by ghost** [yjh0410/FCOS_PyTorch#2]
运行train_voc.py,出现了以下错误
Traceback (most recent call last):
  File "train_voc.py", line 206, in <module>
    train(fcos_lite, device)
  File "train_voc.py", line 151, in train
    cls_loss, ctn_loss, box_loss = tools.loss(out, targets, num_classes=args.num_classes)
  File "/home/eason/桌面/FCOS-tiny/tools.py", line 119, in loss
    cls_loss = torch.mean(cls_loss_func(pred_cls, gt_cls) / N_pos)
  File "/home/eason/anaconda3/envs/FCOS-baby/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/eason/桌面/FCOS-tiny/tools.py", line 14, in forward
    loss = (1.0-inputs)**self.gamma * (targets) * torch.log(inputs + 1e-14) + \
RuntimeError: The size of tensor a (26) must match the size of tensor b (3549) at non-singleton dimension 1

求解决方法QAQ

**Comment by yjh0410** [comment]
忘记更新这个项目了，刚才更新了一下，应该可以了~

**Comment by ghost** [comment]
goooooooood job !!!!
